import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from game.map_loader import MapData, load_map

ASSETS = pathlib.Path(__file__).resolve().parent.parent / "assets" / "maps"


def test_load_map_basic():
    md = load_map("test-map", ASSETS)
    assert isinstance(md, MapData)
    assert md.width == 10
    assert md.tile_width == 32


def test_collision_grid_shape():
    md = load_map("test-map", ASSETS)
    assert len(md.collision) == md.height
    assert all(len(row) == md.width for row in md.collision)


def test_image_path_resolves():
    md = load_map("test-map", ASSETS)
    # test-map.png is generated by scripts/make_test_map.py; may be None until generated
    assert md.image_path is None or md.image_path.exists()


def test_load_tiled_godot_wrapper():
    # bigmap.js is a Tiled export wrapped in the Godot (function(name,data){...}) form.
    md = load_map("bigmap", ASSETS)
    # The real map is the bounding box of placed assets, not the 180x120 canvas.
    assert md.width == 49
    assert md.height == 39
    assert md.tile_width == 32
    assert len(md.tile_layers) == 3
    # No explicit collision layer -> the map is fully walkable.
    blocked = sum(1 for row in md.collision for v in row if v)
    assert blocked == 0
    assert md.is_walkable(*md.spawn)


def test_load_tiled_respects_explicit_collision_layer():
    # A layer literally named "collision" drives blocking, not the base layer.
    data = {
        "width": 3, "height": 2, "tilewidth": 32, "tileheight": 32,
        "layers": [
            {"type": "tilelayer", "name": "ground", "width": 3, "height": 2,
             "data": [1, 1, 1, 1, 1, 1]},
            {"type": "tilelayer", "name": "collision", "width": 3, "height": 2,
             "data": [0, 5, 0, 0, 7, 0]},
        ],
        "tilesets": [],
    }
    import json
    from pathlib import Path
    import tempfile
    tmp = Path(tempfile.mkdtemp()) / "explicit.json"
    tmp.write_text(json.dumps(data), encoding="utf-8")
    md = load_map("explicit", tmp.parent)
    assert sum(1 for row in md.collision for v in row if v) == 2
    assert md.is_walkable(0, 0) and not md.is_walkable(1, 0)


def test_load_tiled_resolves_bundled_tileset_png():
    md = load_map("bigmap", ASSETS)
    # The Pipoya tileset PNG is bundled, so the loader must resolve a real path.
    assert md.tileset is not None
    assert md.tileset["image_path"] is not None
    assert md.tileset["image_path"].exists()
    assert md.tileset["columns"] == 8
    assert md.tileset["firstgid"] == 1
